name: robo_app
description: A robot control app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  awesome_dialog: ^2.1.2
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.17.0
  flutter_phoenix: ^1.0.0
  flutter_staggered_animations: ^1.0.0
  google_fonts: ^2.1.0
  hooks_riverpod: ^0.14.0+4
  http: ^0.13.4
  logger: ^1.1.0
  shared_preferences: ^2.0.9
  url_launcher: ^6.0.15

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/robot_launcher_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
